grpc:
  network: "tcp"
  address: ":50053"
postgres:
  user: "kare"
  password: "pass"
  address: "storage_postgres:5432"
  dbname: "postgres"
  sslmode: "disable"
redis:
  network: "tcp"
  address: "storage_redis:6379"
  password: ""
  db: 0
  lifetimeWrite: "24h"