services:
  app:
    build: .
    ports:
      - 50053:50053
    environment:
      - ConfigPath=config.yaml
    networks:
      - account_control_network

  storage_postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kare
      - POSTGRES_PASSWORD=pass
    networks:
      - account_control_network

  storage_redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - account_control_network

networks:
  account_control_network: